version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27027:27017
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  auth-poc-backend:
    build: .
    container_name: auth-poc-backend
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mypocdb
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped

volumes:
  mongodb_data: 

networks:
  default:
    name: auth-poc-network
